import yarabuilder
import pprint

yara_builder = yarabuilder.YaraBuilder()

yara_builder.create_rule("my_rule")
yara_builder.add_meta("my_rule", "description", "Generated by yarabuilder")
yara_builder.add_import("my_rule", "pe")
yara_builder.add_tag("my_rule", "yarabuilder")
yara_builder.add_text_string("my_rule", "Anonymous string")
yara_builder.add_text_string("my_rule", "Named string", name="str", modifiers=["ascii", "wide"])
yara_builder.add_string_comment("my_rule", "str", "example comment")
yara_builder.add_hex_string("my_rule", "DE AD BE EF")
yara_builder.add_regex_string("my_rule", "regex[0-9]{2}")
yara_builder.add_regex_string("my_rule", "/regex_with_flags/i")
yara_builder.add_condition("my_rule", "any of them")

rule = yara_builder.build_rules()
print(rule)